import { Doctrina, Evento, Iglesia } from "./app/types";

export const zonas = [
  {
    id: 1,
    name: "Zona Norte",
    description: "Zona Norte",
    iglesias: [
      {
        id: 1,
        name: "Arica",
        description: "",
        image: "",
        address: "Av. Concepción # 838 Población Cardenal Raúl Silva Henríquez",
        phone: "",
        email: "",
        website: "",
        pastor: "Martín Chía",
        services: [],
        city: "Arica",
        region: "Arica y Parinacota",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 2,
        name: "Iquique",
        description: "",
        image: "",
        address:
          "La Cantera # 2380 Sede Vecinal Carol Urzúa, Población Jorge Inostroza",
        phone: "",
        email: "",
        website: "",
        pastor: "Cesar Vargas",
        services: [],
        city: "Iquique",
        region: "Tarapacá",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 3,
        name: "Antofagasta",
        description: "",
        image: "",
        address: "Calle Uribe # 542 Centro de Antofagasta",
        phone: "9 82819715",
        email: "fuentealbadonoso79@gmail.com",
        website: "",
        pastor: "Leonardo Luis Fuentealba Donoso",
        services: [],
        city: "Antofagasta",
        region: "Antofagasta",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 4,
        name: "Calama",
        description: "",
        image: "",
        address: "Emiliano Sotomayor # 3250",
        phone: "961002400",
        email: "Cristian.alexander.chavez.1089@gmail.com",
        website: "",
        pastor: "Cristian Alexander Chaves Cortes",
        services: [],
        city: "Antofagasta",
        region: "Antofagasta",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 5,
        name: "Mejillones",
        description: "",
        image: "",
        address: "Pasaje Granaderos # 325",
        phone: "+569 4713 8540",
        email: "Marioperez_32@hotmail.com",
        website: "",
        pastor: "Mario Pérez",
        services: [],
        city: "Mejillones",
        region: "Antofagasta",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 6,
        name: "Tal Tal",
        description: "",
        image: "",
        address: "Calle San Martín # 556, Población El Cobre",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "Tal Tal",
        region: "",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 7,
        name: "Tocopilla",
        description: "",
        image: "",
        address: "Pasaje Prat # 3019",
        phone: "+56991366802",
        email: "h-e-c-t-o-r96@hotmail.com",
        website: "",
        pastor: "Héctor Juan Ruiz Sánchez",
        services: [],
        city: "Tocopilla",
        region: "Antofagasta",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
    ],
  },
  {
    id: 2,
    name: "Zona Centro-Norte",
    description: "Zona Centro-Norte",
    iglesias: [
      {
        id: 8,
        name: "Copiapó",
        description: "",
        image: "",
        address: "Av. Los Loros # 632, Sector Pedro León Gallo",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "Copiapó",
        region: "Atacama",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 9,
        name: "Caldera",
        description: "",
        image: "",
        address: "Av. El Salvador # 807, Centro de Caldera",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "Caldera",
        region: "",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 10,
        name: "Coquimbo",
        description: "",
        image: "",
        address: "Av. Juan de Dios Melgarejo # 851 Centro de Coquimbo",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "Coquimbo",
        region: "",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 11,
        name: "Quilpué",
        description: "",
        image: "",
        address: "Av. María Avellanos / Ernestina # 185",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "Quilpué",
        region: "",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 12,
        name: "La Ligua",
        description: "",
        image: "",
        address: "Calle 2 Oriente # 30, El Peumo",
        phone: "+56947488512",
        email: "jeisonjavzam85@gmail.com",
        website: "",
        pastor: "Yeison Javier Zambrano moreno",
        services: [],
        city: "La Ligua",
        region: "Valparaíso",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
    ],
  },
  {
    id: 3,
    name: "Zona Centro",
    description: "Zona Centro",
    iglesias: [
      {
        id: 121,
        name: "Centro",
        description:
          "Iglesia principal del Movimiento Misionero Mundial en Chile, ubicada en el corazón de Santiago. Un lugar de adoración, enseñanza bíblica y compañerismo cristiano.",
        image: "/images/iglesias/centro.jpeg",
        address: "General Gana #924, Santiago, Región Metropolitana, Chile",
        phone: "+56 975587223",
        email: "secretariammmchile@gmail.com",
        website: "",
        pastor: "Gerardo Martínez",
        services: [
          "Lunes 7:30pm",
          "Martes 7:30pm",
          "Jueves 7:30pm",
          "Viernes 7:00pm",
          "Sábados 5:00pm",
          "Domingos 11:00am",
          "Domingos 5:00pm",
        ],
        city: "Santiago",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: -33.4708573,
        longitude: -70.6481959,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 13,
        name: "Yungay",
        description: "",
        image: "/images/iglesias/yungay.jpeg",
        address: "Mañío # 6665, La Granja",
        phone: "+56 975587223",
        email: "secretariammmchile@gmail.com",
        website: "",
        pastor: "Gerardo Martínez",
        services: ["Miércoles 7:30pm", "Viernes 7:00pm", "Domingos 5:00pm"],
        city: "Santiago",
        region: "Region Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 14,
        name: "San Bernardo",
        description: "",
        image: "",
        address: "Calle José Joaquín Pérez # 662, Centro de San Bernardo",
        phone: "",
        email: "",
        website: "",
        pastor: "Marcelo Quintana",
        services: [],
        city: "San Bernardo",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 15,
        name: "Cerrillos",
        description: "",
        image: "",
        address: "Real Audiencia # 1654, Cerrillos",
        phone: "",
        email: "",
        website: "",
        pastor: "Mauricio Alvarez",
        services: [],
        city: "Cerrillos",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 16,
        name: "Los Almendros",
        description: "",
        image: "",
        address: "Av. Violeta Parra # 1890, La Pintana",
        phone: "+56955251766",
        email: "juan.c.saavedragutierrez@gmail.com ",
        website: "",
        pastor: "Juan Carlos Saavedra Gutierrez",
        services: [],
        city: "La Pintana",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 17,
        name: "Estación Central",
        description: "",
        image: "",
        address: "Calle Toro Mazote # 485 con Av. 5 de Abril, Estación Central",
        phone: "",
        email: "",
        website: "",
        pastor: "Fernando López",
        services: [],
        city: "Santiago",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 18,
        name: "Colina",
        description: "",
        image: "",
        address: "Calle Aconcagua # 364, Colina",
        phone: "+56953199063",
        email: "francisco.saavedra.gut@gmail.com",
        website: "",
        pastor: "Francisco Saavedra",
        services: [],
        city: "Colina",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 19,
        name: "La Portada",
        description: "",
        image: "",
        address: "Santa Marta # 766, San Bernardo",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "La Portada",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 20,
        name: "La Pintana",
        description: "",
        image: "",
        address: "Batallón Chacabuco # 2706, El Castillo, La Pintana",
        phone: "",
        email: "",
        website: "",
        pastor: "Hugo Poblete",
        services: [],
        city: "La Pintana",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 21,
        name: "Rancagua",
        description: "",
        image: "",
        address: "Reconquista # 695, Población Manuel Rodríguez, Rancagua",
        phone: "",
        email: "",
        website: "",
        pastor: "Marcelo Pérez",
        services: [],
        city: "Rancagua",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 22,
        name: "Oscar Bonilla",
        description: "",
        image: "",
        address: "Central # 1309, Población Oscar Bonilla, Rancagua",
        phone: "+56953120056",
        email: "jennyrocioarismendi@gmail.com",
        website: "",
        pastor: "Jenny Rocío Arismendi Torres",
        services: [],
        city: "Rancagua",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 23,
        name: "San Antonio",
        description: "",
        image: "",
        address:
          "Calle 23 de Noviembre # 890, Sector K, Altos Las Cumbres, Placilla, San Antonio",
        phone: "",
        email: "",
        website: "",
        pastor: "Junior Herrera",
        services: [],
        city: "San Antonio",
        region: "Región Metropolitana",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
    ],
  },
  {
    id: 4,
    name: "Zona Centro-Sur",
    description: "Zona Centro-Sur",
    iglesias: [
      {
        id: 24,
        name: "Bobadilla",
        description: "",
        image: "",
        address: "Pasaje Los Rayitos # 65, Bobadilla, San Javier",
        phone: "9-57943087",
        email: "rodrigoconteras93@gmail.com",
        website: "",
        pastor: "Rodrigo Contreras",
        services: [],
        city: "Bobadilla",
        region: "Biobío",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 25,
        name: "Linares",
        description: "",
        image: "",
        address: "Calle Los Salesianos # 1751, Villa Carlos Camus 4, Linares",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "Linares",
        region: "Maule",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 26,
        name: "Chillán",
        description: "",
        image: "",
        address: "Lincoyán # 130 B, Población Mardones",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "Chillán",
        region: "Biobío",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 27,
        name: "Los Angeles",
        description: "",
        image: "",
        address:
          "Calle Bombero Francisco Rioseco # 1910, Población Lo Elvira, Los Ángeles",
        phone: "+56966027478",
        email: "Camposdiazl09@gmail.com ",
        website: "",
        pastor: "Luis Manuel Campos Diaz",
        services: [],
        city: "Los Angeles",
        region: "Biobío",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 28,
        name: "Coronel",
        description: "",
        image: "",
        address: "Manuel Montt # 0663, Villa Mora, Coronel",
        phone: "9-69198141",
        email: "gtguaitiao@gmail.com",
        website: "",
        pastor: "Sergio Hernán Guaitiao queulo",
        services: [],
        city: "Coronel",
        region: "Biobío",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 29,
        name: "Concepción",
        description: "",
        image: "",
        address: "Ventus # 2007, Barrio Norte, Concepción",
        phone: "958561882",
        email: "Alejandrovillalobos444@gmail.com",
        website: "",
        pastor: "Alejandro Villalobos",
        services: [],
        city: "Concepción",
        region: "Biobío",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
    ],
  },
  {
    id: 5,
    name: "Zona Sur",
    description: "Zona Sur",
    iglesias: [
      {
        id: 30,
        name: "Tres Hijuelas",
        description: "",
        image: "",
        address: "Calle del Medio, Parcela # 3, Sector Tres Hijuelas",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "Tres Hijuelas",
        region: "",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 31,
        name: "Temuco",
        description: "",
        image: "",
        address:
          "Los Rosales # 7570, Villa Las Camelias Km. 7 ½ Camino a Labranza, Temuco",
        phone: "",
        email: "",
        website: "",
        pastor: "Victor Mercado",
        services: [],
        city: "Temuco",
        region: "La Araucanía",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 32,
        name: "Villarrica",
        description: "",
        image: "",
        address: "Gabriela Mistral # 670, Ñancul, Villarrica",
        phone: "962255324",
        email: "moisesmunoz. 2021@gmail.com",
        website: "",
        pastor: "Moises Muñoz Huenchumilla",
        services: [],
        city: "Villarrica",
        region: "Araucanía",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 33,
        name: "Panguipulli",
        description: "",
        image: "",
        address: " Kilómetro 7 Ruta 203, Sector Coz Coz, Panguipulli",
        phone: "974459959",
        email: "Antonio.salvo.reyes@gmail.com",
        website: "",
        pastor: "Antonio Salvo reyes",
        services: [],
        city: "",
        region: "",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 34,
        name: "Valdivia",
        description: "",
        image: "",
        address: "Regidor Carrillo # 110, Villa San Luis, Valdivia",
        phone: "+56987717234",
        email: "Pastorjoseperez@gmail.com ",
        website: "",
        pastor: "Jose manuel Perez Caniullan",
        services: [],
        city: "",
        region: "",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 35,
        name: "Osorno",
        description: "",
        image: "",
        address: "Calle Ancud # 1381, Rahue Alto, Osorno",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "Osorno",
        region: "Los Lagos",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
      {
        id: 36,
        name: "Puerto Montt",
        description: "",
        image: "",
        address: "Pasaje Angelmo # 26, Puerto Montt",
        phone: "",
        email: "",
        website: "",
        pastor: "",
        services: [],
        city: "Puerto Montt",
        region: "Los Lagos",
        country: "Chile",
        latitude: 0.0,
        longitude: 0.0,
        createdAt: null,
        updatedAt: null,
        status: "active",
      },
    ],
  },
];

export const doctrina: Doctrina[] = [
  {
    id: 1,
    name: "La Inspiración De Las Sagradas Escrituras",
    description:
      "La Biblia es la Palabra inspirada de Dios... regla infalible de fe y conducta.",
    verses: ["2 Timoteo 3:15-17", "2 Pedro 1:19-21"],
  },
  {
    id: 2,
    name: "La Salvación Por La Fe En Cristo",
    description:
      "La salvación del alma es una transformación... nuevo nacimiento.",
    verses: [
      "Lucas 24:47",
      "Juan 3:16",
      "Romanos 10:13",
      "Tito 2:11",
      "Tito 3:5-7",
    ],
  },
  {
    id: 3,
    name: "Justificación Por La Fe",
    description:
      "Por medio de la fe el hombre puede ser salvo... Cristo es el único mediador.",
    verses: ["Romanos 5:1", "Tito 3:7"],
  },
  {
    id: 4,
    name: "El Bautismo En Agua Por Inmersión",
    description:
      "Toda persona arrepentida debe cumplir el mandato bíblico de bautizarse en agua.",
    verses: ["Mateo 28:19", "Hechos 8:36-39"],
  },
  {
    id: 5,
    name: "El Bautismo En El Espíritu Santo",
    description:
      "El bautismo en el Espíritu Santo es la investidura de poder... hablando en otras lenguas.",
    verses: ["Lucas 24:49", "Hechos 1:4", "Hechos 1:8", "Hechos 2:4"],
  },
  {
    id: 6,
    name: "La Sanidad Divina",
    description:
      "La enfermedad es consecuencia del pecado... provisión para el perdón y la enfermedad.",
    verses: [
      "Isaías 53:4",
      "Mateo 8:16-17",
      "Marcos 16:18",
      "Santiago 5:14-15",
    ],
  },
  {
    id: 7,
    name: "El Fruto Del Espíritu",
    description:
      "Cuando los dones operan, la iglesia no debe olvidar el amor y frutos del Espíritu.",
    verses: ["Gálatas 5:22-26", "Efesios 4:13"],
  },
  {
    id: 8,
    name: "La Santificación",
    description:
      "La verdadera santidad tiene aspecto interno y externo... creer santificado.",
    verses: [
      "1 Tesalonicenses 4:3",
      "1 Tesalonicenses 5:23",
      "Hebreos 12:14",
      "1 Pedro 1:15-16",
      "1 Juan 2:6",
    ],
  },
  {
    id: 9,
    name: "El Ministerio Y La Evangelización",
    description:
      "Los cristianos deben esforzarse en reunión, comunión, servicio, adoración y evangelización.",
    verses: ["Marcos 16:15-20", "Romanos 10:15"],
  },
  {
    id: 10,
    name: "El Diezmo Y El Sostenimiento De La Iglesia",
    description:
      "El creyente debe cumplir obligaciones para sostener a su obra y al obrero.",
    verses: [
      "Génesis 14:20",
      "Génesis 28:22",
      "Levítico 27:30",
      "Números 18:21-26",
      "Malaquías 3:7-10",
      "Mateo 10:10",
      "Mateo 23:23",
    ],
  },
  {
    id: 11,
    name: "El Levantamiento De La Iglesia",
    description:
      "Promesa de Dios de resurrección de los muertos en Cristo para estar con el Señor.",
    verses: [
      "Romanos 8:23",
      "1 Corintios 15:51-52",
      "1 Tesalonicenses 4:16-17",
    ],
  },
  {
    id: 12,
    name: "La Segunda Venida De Cristo",
    description:
      "Después del rapto vendrá la aparición de Cristo... librará Israel del Anticristo.",
    verses: [
      "Zacarías 14:1-9",
      "Mateo 24:30-31",
      "2 Tesalonicenses 1:7",
      "Tito 2:13",
      "Judas 14-15",
    ],
  },
  {
    id: 13,
    name: "El Reino Milenial",
    description:
      "Periodo de mil años donde Cristo reinará sobre la tierra, comenzando tras su segunda venida.",
    verses: [
      "Isaías 2:1-4",
      "Isaías 11:5-10",
      "Zacarías 9:10",
      "Apocalipsis 19:20",
      "Apocalipsis 20:3-10",
    ],
  },
  {
    id: 14,
    name: "Cielos Nuevos Y Tierras Nuevas",
    description:
      "Lugar físico donde moraremos con cuerpos glorificados, libre de pecado y sufrimiento.",
    verses: [
      "Isaías 65:17",
      "Isaías 66:22",
      "2 Pedro 3:13",
      "Apocalipsis 21:1",
    ],
  },
];

export const eventos: Evento[] = [
  {
    id: 1,
    name: "Confraternidad Nacional 2025",
    description:
      "Un encuentro espiritual trascendental que reunirá a pastores, líderes y miembros de todas las iglesias del Movimiento Misionero Mundial en Chile. Durante tres días, nos fortaleceremos en la fe, recibiremos enseñanza bíblica sólida y experimentaremos un avivamiento que transformará nuestras vidas y ministerios. Juntos buscaremos la dirección del Espíritu Santo para avanzar en la misión que Dios nos ha encomendado, fortaleciendo nuestra unidad y compromiso con la evangelización mundial.",
    dateStart: new Date("2025-06-20T00:00:00"),
    dateEnd: new Date("2025-06-22T00:00:00"),
    horarios: ["Viernes", "Sábado", "Domingo"],
    location: "Gimnasio Municipal de Macul",
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3327.634526067217!2d-70.60039222357489!3d-33.4848647992766!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662d021e2bc8ccd%3A0xe15d3ed6fb7c6452!2sGimnasio%20Municipal%20Macul!5e0!3m2!1sen!2scl!4v1749763099896!5m2!1sen!2scl",
    image: "/images/macul.png",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: "Convención Nacional 2025",
    description:
      "La Convención Nacional 2025 será un evento histórico que congregará a toda la familia del Movimiento Misionero Mundial en Chile. Durante este encuentro, profundizaremos en temas fundamentales de nuestra fe, participaremos en talleres de capacitación ministerial y celebraremos la unidad de nuestra iglesia. Será un tiempo especial de renovación espiritual, donde recibiremos nuevas estrategias para la evangelización y fortaleceremos nuestros lazos de comunión. Este evento marcará un antes y un después en nuestro caminar como iglesia en Chile.",
    dateStart: new Date("2025-10-30T00:00:00"),
    dateEnd: new Date("2025-11-02T00:00:00"),
    horarios: [],
    location: "Por confirmar",
    image: "/images/eventos/convencion.jpeg",
    map: "",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
