import { NextResponse } from "next/server";

export async function GET() {
  const data = [
    {
      book: "Salmos",
      chapter: "37",
      verse: "4",
      text: "Deléitate asimismo en Jehová, y él te concederá las peticiones de tu corazón.",
    },
    {
      book: "Isaías",
      chapter: "41",
      verse: "10",
      text: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te fortalezco; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia.",
    },
    {
      book: "Jeremías",
      chapter: "29",
      verse: "11",
      text: "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.",
    },
    {
      book: "Salmos",
      chapter: "23",
      verse: "1",
      text: "Jehová es mi pastor; nada me faltará.",
    },
    {
      book: "Romanos",
      chapter: "8",
      verse: "28",
      text: "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados.",
    },
    {
      book: "Proverbios",
      chapter: "3",
      verse: "5-6",
      text: "Confía en Jehová con todo tu corazón, y no te apoyes en tu propia prudencia. Reconócelo en todos tus caminos, y él enderezará tus veredas.",
    },
    {
      book: "Salmos",
      chapter: "91",
      verse: "15",
      text: "Me invocará, y yo le responderé; con él estaré yo en la angustia; lo libraré y le glorificaré.",
    },
    {
      book: "Mateo",
      chapter: "28",
      verse: "20",
      text: "Enseñándoles que guarden todas las cosas que os he mandado; y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo. Amén.",
    },
    {
      book: "Filipenses",
      chapter: "4",
      verse: "19",
      text: "Mi Dios, pues, suplirá todo lo que os falta conforme a sus riquezas en gloria en Cristo Jesús.",
    },
    {
      book: "Isaías",
      chapter: "54",
      verse: "17",
      text: "Ninguna arma forjada contra ti prosperará, y condenarás toda lengua que se levante contra ti en juicio. Esta es la herencia de los siervos de Jehová, y su justificación de mí parte, dice Jehová.",
    },
    {
      book: "Juan",
      chapter: "14",
      verse: "27",
      text: "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo.",
    },
    {
      book: "Romanos",
      chapter: "15",
      verse: "13",
      text: "Y el Dios de esperanza os llene de todo gozo y paz en el creer, para que abundéis en esperanza por el poder del Espíritu Santo.",
    },
    {
      book: "Salmos",
      chapter: "37",
      verse: "25",
      text: "Fui joven, y he envejecido, y no he visto justo desamparado, ni su descendencia que mendigue pan.",
    },
    {
      book: "Salmos",
      chapter: "46",
      verse: "1",
      text: "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.",
    },
    {
      book: "1 Corintios",
      chapter: "10",
      verse: "13",
      text: "No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir, sino que dará también juntamente con la tentación la salida, para que podáis soportar.",
    },
    {
      book: "1 Pedro",
      chapter: "5",
      verse: "7",
      text: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.",
    },
    {
      book: "2 Pedro",
      chapter: "1",
      verse: "4",
      text: "Por medio de estas cosas nos ha dado preciosas y grandísimas promesas, para que por ellas llegaseis a ser participantes de la naturaleza divina, habiendo huido de la corrupción que hay en el mundo a causa de la concupiscencia.",
    },
    {
      book: "Jeremías",
      chapter: "29",
      verse: "12",
      text: "Entonces me invocaréis, y vendréis y oraréis a mí, y yo os oiré.",
    },
    {
      book: "Hebreos",
      chapter: "13",
      verse: "5",
      text: "Sean vuestras costumbres sin avaricia, contentos con lo que tenéis ahora; porque él dijo: No te desampararé, ni te dejaré.",
    },
    {
      book: "Salmos",
      chapter: "27",
      verse: "10",
      text: "Aunque mi padre y mi madre me dejaran, con todo, Jehová me recogerá.",
    },
    {
      book: "Gálatas",
      chapter: "6",
      verse: "9",
      text: "No nos cansemos, pues, de hacer bien; porque a su tiempo segaremos, si no desmayamos.",
    },
    {
      book: "Juan",
      chapter: "16",
      verse: "33",
      text: "Estas cosas os he hablado para que en mí tengáis paz. En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.",
    },
    {
      book: "Salmos",
      chapter: "34",
      verse: "17",
      text: "Clamaron los justos, y Jehová oyó, y los libró de todas sus angustias.",
    },
    {
      book: "Isaías",
      chapter: "26",
      verse: "3-4",
      text: "Tú guardarás en completa paz a aquel cuyo pensamiento en ti persevera; porque en ti ha confiado. Confiad en Jehová perpetuamente, porque en Jehová el Señor está la fortaleza de los siglos.",
    },
    {
      book: "Mateo",
      chapter: "11",
      verse: "28-30",
      text: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar. Llevad mi yugo sobre vosotros, y aprended de mí, que soy manso y humilde de corazón; y hallaréis descanso para vuestras almas. Porque mi yugo es fácil, y ligera mi carga.",
    },
    {
      book: "Juan",
      chapter: "10",
      verse: "10",
      text: "El ladrón no viene sino para hurtar y matar y destruir; yo he venido para que tengan vida, y para que la tengan en abundancia.",
    },
    {
      book: "Efesios",
      chapter: "3",
      verse: "20",
      text: "Y a Aquel que es poderoso para hacer todas las cosas mucho más abundantemente de lo que pedimos o entendemos, según el poder que actúa en nosotros.",
    },
    {
      book: "Salmos",
      chapter: "103",
      verse: "2-5",
      text: "Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios. Él es quien perdona todas tus iniquidades, el que sana todas tus dolencias; el que rescata del hoyo tu vida, el que te corona de favores y misericordias; el que sacia de bien tu boca de modo que te rejuvenezcas como el águila.",
    },
    {
      book: "Romanos",
      chapter: "8",
      verse: "32",
      text: "El que no escatimó ni a su propio Hijo, sino que lo entregó por todos nosotros, ¿cómo no nos dará también con él todas las cosas?",
    },
    {
      book: "Isaías",
      chapter: "40",
      verse: "31",
      text: "Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán.",
    },
    {
      book: "2 Samuel",
      chapter: "22",
      verse: "31",
      text: "El camino de Dios es perfecto; la palabra de Jehová es probada; es escudo a todos los que en él esperan.",
    },
    {
      book: "1 Juan",
      chapter: "1",
      verse: "9",
      text: "Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad.",
    },
    {
      book: "Salmos",
      chapter: "34",
      verse: "19",
      text: "Muchas son las aflicciones del justo, pero de todas ellas le librará Jehová.",
    },
    {
      book: "Salmos",
      chapter: "91",
      verse: "1-2",
      text: "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente. Diré yo a Jehová: Esperanza mía, y castillo mío; mi Dios, en quien confiaré.",
    },
    {
      book: "Jeremías",
      chapter: "33",
      verse: "3",
      text: "Clama a mí, y yo te responderé, y te enseñaré cosas grandes y ocultas que tú no conoces.",
    },
    {
      book: "Hechos",
      chapter: "1",
      verse: "8",
      text: "Pero recibiréis poder, cuando haya venido sobre vosotros el Espíritu Santo, y me seréis testigos en Jerusalén, en toda Judea, en Samaria, y hasta lo último de la tierra.",
    },
    {
      book: "Romanos",
      chapter: "8",
      verse: "38-39",
      text: "Por lo cual estoy seguro de que ni la muerte, ni la vida, ni ángeles, ni principados, ni potestades, ni lo presente, ni lo por venir, ni lo alto, ni lo profundo, ni ninguna otra cosa creada nos podrá separar del amor de Dios, que es en Cristo Jesús, Señor nuestro.",
    },
    {
      book: "Proverbios",
      chapter: "22",
      verse: "6",
      text: "Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él.",
    },
    {
      book: "2 Crónicas",
      chapter: "7",
      verse: "14",
      text: "si se humillare mi pueblo, sobre el cual mi nombre es invocado, y oraren, y buscaren mi rostro, y se convirtieren de sus malos caminos; entonces yo oiré desde los cielos, perdonaré sus pecados y sanaré su tierra.",
    },
    {
      book: "Salmos",
      chapter: "119",
      verse: "105",
      text: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino.",
    },
    {
      book: "Efesios",
      chapter: "2",
      verse: "8-9",
      text: "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios; no por obras, para que nadie se gloríe.",
    },
    {
      book: "1 Corintios",
      chapter: "16",
      verse: "14",
      text: "Todas vuestras cosas sean hechas con amor.",
    },
  ];

  return NextResponse.json(data);
}
